# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eeeb0e6d36759f636ca21b61855c34dd954cd6c70c60d5743044fb610f0cc6150e4248a59bf63d5e741e79b955109438105c6585f4bf2a23b7581e8c0bb643a8

test:
  secret_key_base: 90425660609a8a9fb5ec87f61308ee837019768d565e2bcdcacfc337eaa557a48144a54bdd7f31645b9324b69b3eee83697da687f1b4935cb39551e35f8cee0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
