# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2efeecf4bf2448769d2afa62c6859de92ac5ac4abd95d142a50aab3f452856b0b36822cc66be0beb3ba9025c35c8bacc2fbcecc06475a92c3c18715f2f56d897
test:
  secret_key_base:  2efeecf4bf2448769d2afa62c6859de92ac5ac4abd95d142a50aab3f452856b0b36822cc66be0beb3ba9025c35c8bacc2fbcecc06475a92c3c18715f2f56d897
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base:  2efeecf4bf2448769d2afa62c6859de92ac5ac4abd95d142a50aab3f452856b0b36822cc66be0beb3ba9025c35c8bacc2fbcecc06475a92c3c18715f2f56d897
  
